/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TranslatedMetadata'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TranslatedMetadata'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.ActivityPoi = factory(root.MusementApi.ApiClient, root.MusementApi.TranslatedMetadata);
  }
}(this, function(ApiClient, TranslatedMetadata) {
  'use strict';




  /**
   * The ActivityPoi model module.
   * @module model/ActivityPoi
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>ActivityPoi</code>.
   * @alias module:model/ActivityPoi
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ActivityPoi</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ActivityPoi} obj Optional instance to populate.
   * @return {module:model/ActivityPoi} The populated <code>ActivityPoi</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
      }
      if (data.hasOwnProperty('types')) {
        obj['types'] = ApiClient.convertToType(data['types'], [TranslatedMetadata]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * @member {Number} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * @member {Array.<module:model/TranslatedMetadata>} types
   */
  exports.prototype['types'] = undefined;



  return exports;
}));


