/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Blogger', 'model/BlogpostCategory', 'model/City'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Blogger'), require('./BlogpostCategory'), require('./City'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.Blogpost = factory(root.MusementApi.ApiClient, root.MusementApi.Blogger, root.MusementApi.BlogpostCategory, root.MusementApi.City);
  }
}(this, function(ApiClient, Blogger, BlogpostCategory, City) {
  'use strict';




  /**
   * The Blogpost model module.
   * @module model/Blogpost
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>Blogpost</code>.
   * @alias module:model/Blogpost
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>Blogpost</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Blogpost} obj Optional instance to populate.
   * @return {module:model/Blogpost} The populated <code>Blogpost</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('abstract')) {
        obj['abstract'] = ApiClient.convertToType(data['abstract'], 'String');
      }
      if (data.hasOwnProperty('publish_date')) {
        obj['publish_date'] = ApiClient.convertToType(data['publish_date'], 'Date');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('background_image')) {
        obj['background_image'] = ApiClient.convertToType(data['background_image'], 'String');
      }
      if (data.hasOwnProperty('background_image_credits')) {
        obj['background_image_credits'] = ApiClient.convertToType(data['background_image_credits'], 'String');
      }
      if (data.hasOwnProperty('categories')) {
        obj['categories'] = ApiClient.convertToType(data['categories'], [BlogpostCategory]);
      }
      if (data.hasOwnProperty('blocks')) {
        obj['blocks'] = ApiClient.convertToType(data['blocks'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = City.constructFromObject(data['city']);
      }
      if (data.hasOwnProperty('author')) {
        obj['author'] = Blogger.constructFromObject(data['author']);
      }
      if (data.hasOwnProperty('share_image')) {
        obj['share_image'] = ApiClient.convertToType(data['share_image'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} abstract
   */
  exports.prototype['abstract'] = undefined;
  /**
   * @member {Date} publish_date
   */
  exports.prototype['publish_date'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {String} background_image
   */
  exports.prototype['background_image'] = undefined;
  /**
   * @member {String} background_image_credits
   */
  exports.prototype['background_image_credits'] = undefined;
  /**
   * @member {Array.<module:model/BlogpostCategory>} categories
   */
  exports.prototype['categories'] = undefined;
  /**
   * @member {String} blocks
   */
  exports.prototype['blocks'] = undefined;
  /**
   * @member {module:model/City} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {module:model/Blogger} author
   */
  exports.prototype['author'] = undefined;
  /**
   * @member {String} share_image
   */
  exports.prototype['share_image'] = undefined;



  return exports;
}));


