/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Blogger', 'model/BlogpostCategory', 'model/City'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Blogger'), require('./BlogpostCategory'), require('./City'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.Blogpost = factory(root.MusementApi.ApiClient, root.MusementApi.Blogger, root.MusementApi.BlogpostCategory, root.MusementApi.City);
  }
}(this, function(ApiClient, Blogger, BlogpostCategory, City) {
  'use strict';




  /**
   * The Blogpost model module.
   * @module model/Blogpost
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>Blogpost</code>.
   * @alias module:model/Blogpost
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>Blogpost</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Blogpost} obj Optional instance to populate.
   * @return {module:model/Blogpost} The populated <code>Blogpost</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('abstract')) {
        obj['abstract'] = ApiClient.convertToType(data['abstract'], 'String');
      }
      if (data.hasOwnProperty('publishDate')) {
        obj['publishDate'] = ApiClient.convertToType(data['publishDate'], 'Date');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('backgroundImage')) {
        obj['backgroundImage'] = ApiClient.convertToType(data['backgroundImage'], 'String');
      }
      if (data.hasOwnProperty('backgroundImageCredits')) {
        obj['backgroundImageCredits'] = ApiClient.convertToType(data['backgroundImageCredits'], 'String');
      }
      if (data.hasOwnProperty('categories')) {
        obj['categories'] = ApiClient.convertToType(data['categories'], [BlogpostCategory]);
      }
      if (data.hasOwnProperty('blocks')) {
        obj['blocks'] = ApiClient.convertToType(data['blocks'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = City.constructFromObject(data['city']);
      }
      if (data.hasOwnProperty('author')) {
        obj['author'] = Blogger.constructFromObject(data['author']);
      }
      if (data.hasOwnProperty('shareImage')) {
        obj['shareImage'] = ApiClient.convertToType(data['shareImage'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} abstract
   */
  exports.prototype['abstract'] = undefined;
  /**
   * @member {Date} publishDate
   */
  exports.prototype['publishDate'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {String} backgroundImage
   */
  exports.prototype['backgroundImage'] = undefined;
  /**
   * @member {String} backgroundImageCredits
   */
  exports.prototype['backgroundImageCredits'] = undefined;
  /**
   * @member {Array.<module:model/BlogpostCategory>} categories
   */
  exports.prototype['categories'] = undefined;
  /**
   * @member {String} blocks
   */
  exports.prototype['blocks'] = undefined;
  /**
   * @member {module:model/City} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {module:model/Blogger} author
   */
  exports.prototype['author'] = undefined;
  /**
   * @member {String} shareImage
   */
  exports.prototype['shareImage'] = undefined;



  return exports;
}));


