/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Customer', 'model/GiftCard', 'model/Price', 'model/PromoCode', 'model/Ticket'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Customer'), require('./GiftCard'), require('./Price'), require('./PromoCode'), require('./Ticket'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.Cart = factory(root.MusementApi.ApiClient, root.MusementApi.Customer, root.MusementApi.GiftCard, root.MusementApi.Price, root.MusementApi.PromoCode, root.MusementApi.Ticket);
  }
}(this, function(ApiClient, Customer, GiftCard, Price, PromoCode, Ticket) {
  'use strict';




  /**
   * The Cart model module.
   * @module model/Cart
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>Cart</code>.
   * @alias module:model/Cart
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>Cart</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Cart} obj Optional instance to populate.
   * @return {module:model/Cart} The populated <code>Cart</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('tickets')) {
        obj['tickets'] = ApiClient.convertToType(data['tickets'], [Ticket]);
      }
      if (data.hasOwnProperty('discount_code')) {
        obj['discount_code'] = ApiClient.convertToType(data['discount_code'], 'String');
      }
      if (data.hasOwnProperty('gift_card')) {
        obj['gift_card'] = GiftCard.constructFromObject(data['gift_card']);
      }
      if (data.hasOwnProperty('promo_code')) {
        obj['promo_code'] = PromoCode.constructFromObject(data['promo_code']);
      }
      if (data.hasOwnProperty('customer')) {
        obj['customer'] = Customer.constructFromObject(data['customer']);
      }
      if (data.hasOwnProperty('customer_id')) {
        obj['customer_id'] = ApiClient.convertToType(data['customer_id'], 'Number');
      }
      if (data.hasOwnProperty('retail_price')) {
        obj['retail_price'] = Price.constructFromObject(data['retail_price']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Array.<module:model/Ticket>} tickets
   */
  exports.prototype['tickets'] = undefined;
  /**
   * This is used only when the cart is posted/put/patched.
   * @member {String} discount_code
   */
  exports.prototype['discount_code'] = undefined;
  /**
   * @member {module:model/GiftCard} gift_card
   */
  exports.prototype['gift_card'] = undefined;
  /**
   * @member {module:model/PromoCode} promo_code
   */
  exports.prototype['promo_code'] = undefined;
  /**
   * @member {module:model/Customer} customer
   */
  exports.prototype['customer'] = undefined;
  /**
   * @member {Number} customer_id
   */
  exports.prototype['customer_id'] = undefined;
  /**
   * @member {module:model/Price} retail_price
   */
  exports.prototype['retail_price'] = undefined;



  return exports;
}));


