/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DestinationCommentAuthor'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DestinationCommentAuthor'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.DestinationComment = factory(root.MusementApi.ApiClient, root.MusementApi.DestinationCommentAuthor);
  }
}(this, function(ApiClient, DestinationCommentAuthor) {
  'use strict';




  /**
   * The DestinationComment model module.
   * @module model/DestinationComment
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>DestinationComment</code>.
   * @alias module:model/DestinationComment
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>DestinationComment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DestinationComment} obj Optional instance to populate.
   * @return {module:model/DestinationComment} The populated <code>DestinationComment</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('author')) {
        obj['author'] = DestinationCommentAuthor.constructFromObject(data['author']);
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('text')) {
        obj['text'] = ApiClient.convertToType(data['text'], 'String');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/DestinationCommentAuthor} author
   */
  exports.prototype['author'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} text
   */
  exports.prototype['text'] = undefined;
  /**
   * This value is saved as ISO 8601 string.
   * @member {String} date
   */
  exports.prototype['date'] = undefined;



  return exports;
}));


