/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Bucket', 'model/Category', 'model/City', 'model/Flavour', 'model/Price', 'model/Tag', 'model/TranslatedMetadata', 'model/Vertical'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Bucket'), require('./Category'), require('./City'), require('./Flavour'), require('./Price'), require('./Tag'), require('./TranslatedMetadata'), require('./Vertical'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.Event = factory(root.MusementApi.ApiClient, root.MusementApi.Bucket, root.MusementApi.Category, root.MusementApi.City, root.MusementApi.Flavour, root.MusementApi.Price, root.MusementApi.Tag, root.MusementApi.TranslatedMetadata, root.MusementApi.Vertical);
  }
}(this, function(ApiClient, Bucket, Category, City, Flavour, Price, Tag, TranslatedMetadata, Vertical) {
  'use strict';




  /**
   * The Event model module.
   * @module model/Event
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>Event</code>.
   * @alias module:model/Event
   * @class
   */
  var exports = function() {
    var _this = this;

































































  };

  /**
   * Constructs a <code>Event</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Event} obj Optional instance to populate.
   * @return {module:model/Event} The populated <code>Event</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = City.constructFromObject(data['city']);
      }
      if (data.hasOwnProperty('saves')) {
        obj['saves'] = ApiClient.convertToType(data['saves'], 'Number');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('relevance')) {
        obj['relevance'] = ApiClient.convertToType(data['relevance'], 'Number');
      }
      if (data.hasOwnProperty('relevanceVenue')) {
        obj['relevanceVenue'] = ApiClient.convertToType(data['relevanceVenue'], 'Number');
      }
      if (data.hasOwnProperty('maxConfirmationTime')) {
        obj['maxConfirmationTime'] = ApiClient.convertToType(data['maxConfirmationTime'], 'Number');
      }
      if (data.hasOwnProperty('mustSee')) {
        obj['mustSee'] = ApiClient.convertToType(data['mustSee'], 'Boolean');
      }
      if (data.hasOwnProperty('lastChance')) {
        obj['lastChance'] = ApiClient.convertToType(data['lastChance'], 'Boolean');
      }
      if (data.hasOwnProperty('topSeller')) {
        obj['topSeller'] = ApiClient.convertToType(data['topSeller'], 'Boolean');
      }
      if (data.hasOwnProperty('printVoucher')) {
        obj['printVoucher'] = ApiClient.convertToType(data['printVoucher'], 'Boolean');
      }
      if (data.hasOwnProperty('temporary')) {
        obj['temporary'] = ApiClient.convertToType(data['temporary'], 'Boolean');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('about')) {
        obj['about'] = ApiClient.convertToType(data['about'], 'String');
      }
      if (data.hasOwnProperty('aboutMarkdown')) {
        obj['aboutMarkdown'] = ApiClient.convertToType(data['aboutMarkdown'], 'String');
      }
      if (data.hasOwnProperty('aboutHtml')) {
        obj['aboutHtml'] = ApiClient.convertToType(data['aboutHtml'], 'String');
      }
      if (data.hasOwnProperty('meetingPoint')) {
        obj['meetingPoint'] = ApiClient.convertToType(data['meetingPoint'], 'String');
      }
      if (data.hasOwnProperty('openingHours')) {
        obj['openingHours'] = ApiClient.convertToType(data['openingHours'], 'String');
      }
      if (data.hasOwnProperty('numberedSeats')) {
        obj['numberedSeats'] = ApiClient.convertToType(data['numberedSeats'], 'Boolean');
      }
      if (data.hasOwnProperty('hasPriceInfoOnDate')) {
        obj['hasPriceInfoOnDate'] = ApiClient.convertToType(data['hasPriceInfoOnDate'], 'Boolean');
      }
      if (data.hasOwnProperty('open')) {
        obj['open'] = ApiClient.convertToType(data['open'], 'Boolean');
      }
      if (data.hasOwnProperty('ticketNotIncluded')) {
        obj['ticketNotIncluded'] = ApiClient.convertToType(data['ticketNotIncluded'], 'Boolean');
      }
      if (data.hasOwnProperty('likelyToSellOut')) {
        obj['likelyToSellOut'] = ApiClient.convertToType(data['likelyToSellOut'], 'Boolean');
      }
      if (data.hasOwnProperty('specialOffer')) {
        obj['specialOffer'] = ApiClient.convertToType(data['specialOffer'], 'Boolean');
      }
      if (data.hasOwnProperty('exclusive')) {
        obj['exclusive'] = ApiClient.convertToType(data['exclusive'], 'Boolean');
      }
      if (data.hasOwnProperty('includedHotelNightNumber')) {
        obj['includedHotelNightNumber'] = ApiClient.convertToType(data['includedHotelNightNumber'], 'Number');
      }
      if (data.hasOwnProperty('greenFeeDays')) {
        obj['greenFeeDays'] = ApiClient.convertToType(data['greenFeeDays'], 'Number');
      }
      if (data.hasOwnProperty('daily')) {
        obj['daily'] = ApiClient.convertToType(data['daily'], 'Boolean');
      }
      if (data.hasOwnProperty('languages')) {
        obj['languages'] = ApiClient.convertToType(data['languages'], [TranslatedMetadata]);
      }
      if (data.hasOwnProperty('groupSize')) {
        obj['groupSize'] = ApiClient.convertToType(data['groupSize'], ['String']);
      }
      if (data.hasOwnProperty('food')) {
        obj['food'] = ApiClient.convertToType(data['food'], [TranslatedMetadata]);
      }
      if (data.hasOwnProperty('services')) {
        obj['services'] = ApiClient.convertToType(data['services'], [TranslatedMetadata]);
      }
      if (data.hasOwnProperty('translated')) {
        obj['translated'] = ApiClient.convertToType(data['translated'], ['String']);
      }
      if (data.hasOwnProperty('features')) {
        obj['features'] = ApiClient.convertToType(data['features'], [TranslatedMetadata]);
      }
      if (data.hasOwnProperty('highlights')) {
        obj['highlights'] = ApiClient.convertToType(data['highlights'], ['String']);
      }
      if (data.hasOwnProperty('included')) {
        obj['included'] = ApiClient.convertToType(data['included'], ['String']);
      }
      if (data.hasOwnProperty('notIncluded')) {
        obj['notIncluded'] = ApiClient.convertToType(data['notIncluded'], ['String']);
      }
      if (data.hasOwnProperty('isAvailableToday')) {
        obj['isAvailableToday'] = ApiClient.convertToType(data['isAvailableToday'], 'Boolean');
      }
      if (data.hasOwnProperty('isAvailableTomorrow')) {
        obj['isAvailableTomorrow'] = ApiClient.convertToType(data['isAvailableTomorrow'], 'Boolean');
      }
      if (data.hasOwnProperty('hasMultipleOptions')) {
        obj['hasMultipleOptions'] = ApiClient.convertToType(data['hasMultipleOptions'], 'Boolean');
      }
      if (data.hasOwnProperty('coverImageUrl')) {
        obj['coverImageUrl'] = ApiClient.convertToType(data['coverImageUrl'], 'String');
      }
      if (data.hasOwnProperty('extraMediaUrl')) {
        obj['extraMediaUrl'] = ApiClient.convertToType(data['extraMediaUrl'], 'String');
      }
      if (data.hasOwnProperty('retailPrice')) {
        obj['retailPrice'] = Price.constructFromObject(data['retailPrice']);
      }
      if (data.hasOwnProperty('netPrice')) {
        obj['netPrice'] = Price.constructFromObject(data['netPrice']);
      }
      if (data.hasOwnProperty('bundledPrice')) {
        obj['bundledPrice'] = Price.constructFromObject(data['bundledPrice']);
      }
      if (data.hasOwnProperty('discount')) {
        obj['discount'] = ApiClient.convertToType(data['discount'], 'Number');
      }
      if (data.hasOwnProperty('bucket')) {
        obj['bucket'] = Bucket.constructFromObject(data['bucket']);
      }
      if (data.hasOwnProperty('categories')) {
        obj['categories'] = ApiClient.convertToType(data['categories'], [Category]);
      }
      if (data.hasOwnProperty('reviewsNumber')) {
        obj['reviewsNumber'] = ApiClient.convertToType(data['reviewsNumber'], 'Number');
      }
      if (data.hasOwnProperty('reviewsAvg')) {
        obj['reviewsAvg'] = ApiClient.convertToType(data['reviewsAvg'], 'Number');
      }
      if (data.hasOwnProperty('reviewsAggregatedInfo')) {
        obj['reviewsAggregatedInfo'] = ApiClient.convertToType(data['reviewsAggregatedInfo'], ['String']);
      }
      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('agencyUrls')) {
        obj['agencyUrls'] = ApiClient.convertToType(data['agencyUrls'], ['String']);
      }
      if (data.hasOwnProperty('agencyPrice')) {
        obj['agencyPrice'] = Price.constructFromObject(data['agencyPrice']);
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], [Tag]);
      }
      if (data.hasOwnProperty('flavours')) {
        obj['flavours'] = ApiClient.convertToType(data['flavours'], [Flavour]);
      }
      if (data.hasOwnProperty('verticals')) {
        obj['verticals'] = ApiClient.convertToType(data['verticals'], [Vertical]);
      }
      if (data.hasOwnProperty('orderBoxElements')) {
        obj['orderBoxElements'] = ApiClient.convertToType(data['orderBoxElements'], ['String']);
      }
      if (data.hasOwnProperty('giftable')) {
        obj['giftable'] = ApiClient.convertToType(data['giftable'], 'Boolean');
      }
      if (data.hasOwnProperty('hasPassengerInfo')) {
        obj['hasPassengerInfo'] = ApiClient.convertToType(data['hasPassengerInfo'], 'Boolean');
      }
      if (data.hasOwnProperty('hasExtraCustomerData')) {
        obj['hasExtraCustomerData'] = ApiClient.convertToType(data['hasExtraCustomerData'], 'Boolean');
      }
      if (data.hasOwnProperty('realtimeCapable')) {
        obj['realtimeCapable'] = ApiClient.convertToType(data['realtimeCapable'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Event unique identifier
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;
  /**
   * @member {module:model/City} city
   */
  exports.prototype['city'] = undefined;
  /**
   * Number of customer who saved this city as favorite
   * @member {Number} saves
   */
  exports.prototype['saves'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {Number} relevance
   */
  exports.prototype['relevance'] = undefined;
  /**
   * @member {Number} relevanceVenue
   */
  exports.prototype['relevanceVenue'] = undefined;
  /**
   * @member {Number} maxConfirmationTime
   */
  exports.prototype['maxConfirmationTime'] = undefined;
  /**
   * @member {Boolean} mustSee
   */
  exports.prototype['mustSee'] = undefined;
  /**
   * @member {Boolean} lastChance
   */
  exports.prototype['lastChance'] = undefined;
  /**
   * @member {Boolean} topSeller
   */
  exports.prototype['topSeller'] = undefined;
  /**
   * Voucher must be printed to access the activity
   * @member {Boolean} printVoucher
   */
  exports.prototype['printVoucher'] = undefined;
  /**
   * @member {Boolean} temporary
   */
  exports.prototype['temporary'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} about
   */
  exports.prototype['about'] = undefined;
  /**
   * @member {String} aboutMarkdown
   */
  exports.prototype['aboutMarkdown'] = undefined;
  /**
   * @member {String} aboutHtml
   */
  exports.prototype['aboutHtml'] = undefined;
  /**
   * @member {String} meetingPoint
   */
  exports.prototype['meetingPoint'] = undefined;
  /**
   * @member {String} openingHours
   */
  exports.prototype['openingHours'] = undefined;
  /**
   * @member {Boolean} numberedSeats
   */
  exports.prototype['numberedSeats'] = undefined;
  /**
   * If true the call GET /events/{id}/dates returns prices for each day.
   * @member {Boolean} hasPriceInfoOnDate
   */
  exports.prototype['hasPriceInfoOnDate'] = undefined;
  /**
   * Define if the Event is with open dates entrance (aka: Event::isOpenTicket).
   * @member {Boolean} open
   */
  exports.prototype['open'] = undefined;
  /**
   * @member {Boolean} ticketNotIncluded
   */
  exports.prototype['ticketNotIncluded'] = undefined;
  /**
   * @member {Boolean} likelyToSellOut
   */
  exports.prototype['likelyToSellOut'] = undefined;
  /**
   * @member {Boolean} specialOffer
   */
  exports.prototype['specialOffer'] = undefined;
  /**
   * @member {Boolean} exclusive
   */
  exports.prototype['exclusive'] = undefined;
  /**
   * @member {Number} includedHotelNightNumber
   */
  exports.prototype['includedHotelNightNumber'] = undefined;
  /**
   * @member {Number} greenFeeDays
   */
  exports.prototype['greenFeeDays'] = undefined;
  /**
   * Define if the Event is with \"daily tickets\" (aka: Event::getDailyTickets) This causes for example: to hide \"time block\" in Orderbox.
   * @member {Boolean} daily
   */
  exports.prototype['daily'] = undefined;
  /**
   * @member {Array.<module:model/TranslatedMetadata>} languages
   */
  exports.prototype['languages'] = undefined;
  /**
   * @member {Array.<String>} groupSize
   */
  exports.prototype['groupSize'] = undefined;
  /**
   * @member {Array.<module:model/TranslatedMetadata>} food
   */
  exports.prototype['food'] = undefined;
  /**
   * @member {Array.<module:model/TranslatedMetadata>} services
   */
  exports.prototype['services'] = undefined;
  /**
   * @member {Array.<String>} translated
   */
  exports.prototype['translated'] = undefined;
  /**
   * @member {Array.<module:model/TranslatedMetadata>} features
   */
  exports.prototype['features'] = undefined;
  /**
   * @member {Array.<String>} highlights
   */
  exports.prototype['highlights'] = undefined;
  /**
   * @member {Array.<String>} included
   */
  exports.prototype['included'] = undefined;
  /**
   * @member {Array.<String>} notIncluded
   */
  exports.prototype['notIncluded'] = undefined;
  /**
   * @member {Boolean} isAvailableToday
   */
  exports.prototype['isAvailableToday'] = undefined;
  /**
   * @member {Boolean} isAvailableTomorrow
   */
  exports.prototype['isAvailableTomorrow'] = undefined;
  /**
   * @member {Boolean} hasMultipleOptions
   */
  exports.prototype['hasMultipleOptions'] = undefined;
  /**
   * @member {String} coverImageUrl
   */
  exports.prototype['coverImageUrl'] = undefined;
  /**
   * @member {String} extraMediaUrl
   */
  exports.prototype['extraMediaUrl'] = undefined;
  /**
   * @member {module:model/Price} retailPrice
   */
  exports.prototype['retailPrice'] = undefined;
  /**
   * @member {module:model/Price} netPrice
   */
  exports.prototype['netPrice'] = undefined;
  /**
   * @member {module:model/Price} bundledPrice
   */
  exports.prototype['bundledPrice'] = undefined;
  /**
   * @member {Number} discount
   */
  exports.prototype['discount'] = undefined;
  /**
   * @member {module:model/Bucket} bucket
   */
  exports.prototype['bucket'] = undefined;
  /**
   * @member {Array.<module:model/Category>} categories
   */
  exports.prototype['categories'] = undefined;
  /**
   * @member {Number} reviewsNumber
   */
  exports.prototype['reviewsNumber'] = undefined;
  /**
   * @member {Number} reviewsAvg
   */
  exports.prototype['reviewsAvg'] = undefined;
  /**
   * @member {Array.<String>} reviewsAggregatedInfo
   */
  exports.prototype['reviewsAggregatedInfo'] = undefined;
  /**
   * @member {Number} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * @member {Number} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {Array.<String>} agencyUrls
   */
  exports.prototype['agencyUrls'] = undefined;
  /**
   * @member {module:model/Price} agencyPrice
   */
  exports.prototype['agencyPrice'] = undefined;
  /**
   * @member {Array.<module:model/Tag>} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * @member {Array.<module:model/Flavour>} flavours
   */
  exports.prototype['flavours'] = undefined;
  /**
   * @member {Array.<module:model/Vertical>} verticals
   */
  exports.prototype['verticals'] = undefined;
  /**
   * @member {Array.<String>} orderBoxElements
   */
  exports.prototype['orderBoxElements'] = undefined;
  /**
   * @member {Boolean} giftable
   */
  exports.prototype['giftable'] = undefined;
  /**
   * @member {Boolean} hasPassengerInfo
   */
  exports.prototype['hasPassengerInfo'] = undefined;
  /**
   * @member {Boolean} hasExtraCustomerData
   */
  exports.prototype['hasExtraCustomerData'] = undefined;
  /**
   * Define if the Event is \"realtimeCapable\".
   * @member {Boolean} realtimeCapable
   */
  exports.prototype['realtimeCapable'] = undefined;



  return exports;
}));


