/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Event'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Event'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.FeedbackRequest = factory(root.MusementApi.ApiClient, root.MusementApi.Event);
  }
}(this, function(ApiClient, Event) {
  'use strict';




  /**
   * The FeedbackRequest model module.
   * @module model/FeedbackRequest
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>FeedbackRequest</code>.
   * @alias module:model/FeedbackRequest
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>FeedbackRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FeedbackRequest} obj Optional instance to populate.
   * @return {module:model/FeedbackRequest} The populated <code>FeedbackRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('nonce')) {
        obj['nonce'] = ApiClient.convertToType(data['nonce'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('event')) {
        obj['event'] = Event.constructFromObject(data['event']);
      }
    }
    return obj;
  }

  /**
   * @member {String} nonce
   */
  exports.prototype['nonce'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {module:model/Event} event
   */
  exports.prototype['event'] = undefined;



  return exports;
}));


