/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.FormFieldError = factory(root.MusementApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FormFieldError model module.
   * @module model/FormFieldError
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>FormFieldError</code>.
   * @alias module:model/FormFieldError
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>FormFieldError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FormFieldError} obj Optional instance to populate.
   * @return {module:model/FormFieldError} The populated <code>FormFieldError</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fieldName')) {
        obj['fieldName'] = ApiClient.convertToType(data['fieldName'], 'String');
      }
      if (data.hasOwnProperty('fieldErrorMessage')) {
        obj['fieldErrorMessage'] = ApiClient.convertToType(data['fieldErrorMessage'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} fieldName
   */
  exports.prototype['fieldName'] = undefined;
  /**
   * @member {String} fieldErrorMessage
   */
  exports.prototype['fieldErrorMessage'] = undefined;



  return exports;
}));


