/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GiftCreationProductWithQuantity'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GiftCreationProductWithQuantity'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.GiftCreationRequest = factory(root.MusementApi.ApiClient, root.MusementApi.GiftCreationProductWithQuantity);
  }
}(this, function(ApiClient, GiftCreationProductWithQuantity) {
  'use strict';




  /**
   * The GiftCreationRequest model module.
   * @module model/GiftCreationRequest
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>GiftCreationRequest</code>.
   * @alias module:model/GiftCreationRequest
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>GiftCreationRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GiftCreationRequest} obj Optional instance to populate.
   * @return {module:model/GiftCreationRequest} The populated <code>GiftCreationRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('event_id')) {
        obj['event_id'] = ApiClient.convertToType(data['event_id'], 'Number');
      }
      if (data.hasOwnProperty('donor_name')) {
        obj['donor_name'] = ApiClient.convertToType(data['donor_name'], 'String');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('picture_url')) {
        obj['picture_url'] = ApiClient.convertToType(data['picture_url'], 'String');
      }
      if (data.hasOwnProperty('print')) {
        obj['print'] = ApiClient.convertToType(data['print'], 'Boolean');
      }
      if (data.hasOwnProperty('recipient_email')) {
        obj['recipient_email'] = ApiClient.convertToType(data['recipient_email'], 'String');
      }
      if (data.hasOwnProperty('recipient_name')) {
        obj['recipient_name'] = ApiClient.convertToType(data['recipient_name'], 'String');
      }
      if (data.hasOwnProperty('feature_code')) {
        obj['feature_code'] = ApiClient.convertToType(data['feature_code'], 'String');
      }
      if (data.hasOwnProperty('products_with_quantities')) {
        obj['products_with_quantities'] = ApiClient.convertToType(data['products_with_quantities'], [GiftCreationProductWithQuantity]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} event_id
   */
  exports.prototype['event_id'] = undefined;
  /**
   * @member {String} donor_name
   */
  exports.prototype['donor_name'] = undefined;
  /**
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * @member {String} picture_url
   */
  exports.prototype['picture_url'] = undefined;
  /**
   * @member {Boolean} print
   */
  exports.prototype['print'] = undefined;
  /**
   * Optional if print is true.
   * @member {String} recipient_email
   */
  exports.prototype['recipient_email'] = undefined;
  /**
   * @member {String} recipient_name
   */
  exports.prototype['recipient_name'] = undefined;
  /**
   * @member {String} feature_code
   */
  exports.prototype['feature_code'] = undefined;
  /**
   * @member {Array.<module:model/GiftCreationProductWithQuantity>} products_with_quantities
   */
  exports.prototype['products_with_quantities'] = undefined;



  return exports;
}));


