/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/City', 'model/Customer', 'model/ListType', 'model/Vertical'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./City'), require('./Customer'), require('./ListType'), require('./Vertical'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.MusementList = factory(root.MusementApi.ApiClient, root.MusementApi.City, root.MusementApi.Customer, root.MusementApi.ListType, root.MusementApi.Vertical);
  }
}(this, function(ApiClient, City, Customer, ListType, Vertical) {
  'use strict';




  /**
   * The MusementList model module.
   * @module model/MusementList
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>MusementList</code>.
   * @alias module:model/MusementList
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>MusementList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MusementList} obj Optional instance to populate.
   * @return {module:model/MusementList} The populated <code>MusementList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('authors')) {
        obj['authors'] = ApiClient.convertToType(data['authors'], [Customer]);
      }
      if (data.hasOwnProperty('views')) {
        obj['views'] = ApiClient.convertToType(data['views'], 'Number');
      }
      if (data.hasOwnProperty('scroll')) {
        obj['scroll'] = ApiClient.convertToType(data['scroll'], 'Number');
      }
      if (data.hasOwnProperty('saves')) {
        obj['saves'] = ApiClient.convertToType(data['saves'], 'Number');
      }
      if (data.hasOwnProperty('list_type')) {
        obj['list_type'] = ListType.constructFromObject(data['list_type']);
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = City.constructFromObject(data['city']);
      }
      if (data.hasOwnProperty('cover_image_url')) {
        obj['cover_image_url'] = ApiClient.convertToType(data['cover_image_url'], 'String');
      }
      if (data.hasOwnProperty('verticals')) {
        obj['verticals'] = ApiClient.convertToType(data['verticals'], [Vertical]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Array.<module:model/Customer>} authors
   */
  exports.prototype['authors'] = undefined;
  /**
   * @member {Number} views
   */
  exports.prototype['views'] = undefined;
  /**
   * @member {Number} scroll
   */
  exports.prototype['scroll'] = undefined;
  /**
   * @member {Number} saves
   */
  exports.prototype['saves'] = undefined;
  /**
   * @member {module:model/ListType} list_type
   */
  exports.prototype['list_type'] = undefined;
  /**
   * @member {module:model/City} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {String} cover_image_url
   */
  exports.prototype['cover_image_url'] = undefined;
  /**
   * @member {Array.<module:model/Vertical>} verticals
   */
  exports.prototype['verticals'] = undefined;



  return exports;
}));


