/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PutCustomer'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PutCustomer'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.PatchCustomer = factory(root.MusementApi.ApiClient, root.MusementApi.PutCustomer);
  }
}(this, function(ApiClient, PutCustomer) {
  'use strict';




  /**
   * The PatchCustomer model module.
   * @module model/PatchCustomer
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>PatchCustomer</code>.
   * @alias module:model/PatchCustomer
   * @class
   * @extends module:model/PutCustomer
   * @param firstname {String} Customer's first name
   * @param lastname {String} Customer's last name
   * @param city {String} Customer's city (free text)
   * @param address {String} Customer's street address
   * @param birthdate {String} Date of birth of the customer, ICU format: 'yyyy-MM-dd'
   * @param emailNotificationEnabled {Boolean} Customer email notification enabling flag
   * @param promotionSubscribed {Boolean} Customer promotion subscription flag
   * @param newsletterSubscribed {Boolean} Customer newsletter subscription flag
   * @param country {String} Customer's country 2 char notation iso code
   */
  var exports = function(firstname, lastname, city, address, birthdate, emailNotificationEnabled, promotionSubscribed, newsletterSubscribed, country) {
    var _this = this;
    PutCustomer.call(_this, firstname, lastname, city, address, birthdate, emailNotificationEnabled, promotionSubscribed, newsletterSubscribed, country);
  };

  /**
   * Constructs a <code>PatchCustomer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PatchCustomer} obj Optional instance to populate.
   * @return {module:model/PatchCustomer} The populated <code>PatchCustomer</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      PutCustomer.constructFromObject(data, obj);
    }
    return obj;
  }

  exports.prototype = Object.create(PutCustomer.prototype);
  exports.prototype.constructor = exports;




  return exports;
}));


