/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.PaypalPaymentRequest = factory(root.MusementApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PaypalPaymentRequest model module.
   * @module model/PaypalPaymentRequest
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>PaypalPaymentRequest</code>.
   * @alias module:model/PaypalPaymentRequest
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>PaypalPaymentRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaypalPaymentRequest} obj Optional instance to populate.
   * @return {module:model/PaypalPaymentRequest} The populated <code>PaypalPaymentRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('order_id')) {
        obj['order_id'] = ApiClient.convertToType(data['order_id'], 'Number');
      }
      if (data.hasOwnProperty('paypal_payment_id')) {
        obj['paypal_payment_id'] = ApiClient.convertToType(data['paypal_payment_id'], 'String');
      }
      if (data.hasOwnProperty('client_ip')) {
        obj['client_ip'] = ApiClient.convertToType(data['client_ip'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} order_id
   */
  exports.prototype['order_id'] = undefined;
  /**
   * Paypal \"payment id\" obtained on \"client side\".
   * @member {String} paypal_payment_id
   */
  exports.prototype['paypal_payment_id'] = undefined;
  /**
   * [optional] User IP address for logging purposes.
   * @member {String} client_ip
   */
  exports.prototype['client_ip'] = undefined;



  return exports;
}));


