/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Event', 'model/Price', 'model/Pricetag'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Event'), require('./Price'), require('./Pricetag'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.SeatPrice = factory(root.MusementApi.ApiClient, root.MusementApi.Event, root.MusementApi.Price, root.MusementApi.Pricetag);
  }
}(this, function(ApiClient, Event, Price, Pricetag) {
  'use strict';




  /**
   * The SeatPrice model module.
   * @module model/SeatPrice
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>SeatPrice</code>.
   * @alias module:model/SeatPrice
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>SeatPrice</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SeatPrice} obj Optional instance to populate.
   * @return {module:model/SeatPrice} The populated <code>SeatPrice</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('event')) {
        obj['event'] = Event.constructFromObject(data['event']);
      }
      if (data.hasOwnProperty('price_tag')) {
        obj['price_tag'] = Pricetag.constructFromObject(data['price_tag']);
      }
      if (data.hasOwnProperty('raw_price')) {
        obj['raw_price'] = Price.constructFromObject(data['raw_price']);
      }
      if (data.hasOwnProperty('discount_amount')) {
        obj['discount_amount'] = Price.constructFromObject(data['discount_amount']);
      }
      if (data.hasOwnProperty('retail_price')) {
        obj['retail_price'] = Price.constructFromObject(data['retail_price']);
      }
      if (data.hasOwnProperty('service_fee')) {
        obj['service_fee'] = Price.constructFromObject(data['service_fee']);
      }
      if (data.hasOwnProperty('datetime')) {
        obj['datetime'] = ApiClient.convertToType(data['datetime'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/Event} event
   */
  exports.prototype['event'] = undefined;
  /**
   * @member {module:model/Pricetag} price_tag
   */
  exports.prototype['price_tag'] = undefined;
  /**
   * This is the price to the user without any discount applied. (same currency as retailPrice)
   * @member {module:model/Price} raw_price
   */
  exports.prototype['raw_price'] = undefined;
  /**
   * Amount of discount in same currency as retailPrice (only SeatPrice.discount used because its not in Cart)
   * @member {module:model/Price} discount_amount
   */
  exports.prototype['discount_amount'] = undefined;
  /**
   * Price with discount applied (only SeatPrice.discount used because its not in Cart)
   * @member {module:model/Price} retail_price
   */
  exports.prototype['retail_price'] = undefined;
  /**
   * @member {module:model/Price} service_fee
   */
  exports.prototype['service_fee'] = undefined;
  /**
   * @member {Number} datetime
   */
  exports.prototype['datetime'] = undefined;



  return exports;
}));


