/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.StripePaymentRequest = factory(root.MusementApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The StripePaymentRequest model module.
   * @module model/StripePaymentRequest
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>StripePaymentRequest</code>.
   * @alias module:model/StripePaymentRequest
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>StripePaymentRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StripePaymentRequest} obj Optional instance to populate.
   * @return {module:model/StripePaymentRequest} The populated <code>StripePaymentRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('orderId')) {
        obj['orderId'] = ApiClient.convertToType(data['orderId'], 'Number');
      }
      if (data.hasOwnProperty('clientIp')) {
        obj['clientIp'] = ApiClient.convertToType(data['clientIp'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} orderId
   */
  exports.prototype['orderId'] = undefined;
  /**
   * [optional] User IP address for logging purposes.
   * @member {String} clientIp
   */
  exports.prototype['clientIp'] = undefined;



  return exports;
}));


