/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/City', 'model/Country', 'model/Event', 'model/Vertical'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./City'), require('./Country'), require('./Event'), require('./Vertical'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.Venue = factory(root.MusementApi.ApiClient, root.MusementApi.City, root.MusementApi.Country, root.MusementApi.Event, root.MusementApi.Vertical);
  }
}(this, function(ApiClient, City, Country, Event, Vertical) {
  'use strict';




  /**
   * The Venue model module.
   * @module model/Venue
   * @version 3.2.0
   */

  /**
   * Constructs a new <code>Venue</code>.
   * @alias module:model/Venue
   * @class
   */
  var exports = function() {
    var _this = this;




















  };

  /**
   * Constructs a <code>Venue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Venue} obj Optional instance to populate.
   * @return {module:model/Venue} The populated <code>Venue</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = City.constructFromObject(data['city']);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('headline')) {
        obj['headline'] = ApiClient.convertToType(data['headline'], 'String');
      }
      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
      }
      if (data.hasOwnProperty('relevance')) {
        obj['relevance'] = ApiClient.convertToType(data['relevance'], 'Number');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('description_html')) {
        obj['description_html'] = ApiClient.convertToType(data['description_html'], 'String');
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('events')) {
        obj['events'] = ApiClient.convertToType(data['events'], [Event]);
      }
      if (data.hasOwnProperty('verticals')) {
        obj['verticals'] = ApiClient.convertToType(data['verticals'], [Vertical]);
      }
      if (data.hasOwnProperty('cover_image_url')) {
        obj['cover_image_url'] = ApiClient.convertToType(data['cover_image_url'], 'String');
      }
      if (data.hasOwnProperty('events_count')) {
        obj['events_count'] = ApiClient.convertToType(data['events_count'], 'Number');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = Country.constructFromObject(data['country']);
      }
      if (data.hasOwnProperty('show_calendar')) {
        obj['show_calendar'] = ApiClient.convertToType(data['show_calendar'], 'Boolean');
      }
      if (data.hasOwnProperty('show_flavours_filter')) {
        obj['show_flavours_filter'] = ApiClient.convertToType(data['show_flavours_filter'], 'Boolean');
      }
      if (data.hasOwnProperty('show_filters_when_events_count')) {
        obj['show_filters_when_events_count'] = ApiClient.convertToType(data['show_filters_when_events_count'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/City} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} headline
   */
  exports.prototype['headline'] = undefined;
  /**
   * @member {Number} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * @member {Number} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * @member {Number} relevance
   */
  exports.prototype['relevance'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} description_html
   */
  exports.prototype['description_html'] = undefined;
  /**
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {Array.<module:model/Event>} events
   */
  exports.prototype['events'] = undefined;
  /**
   * @member {Array.<module:model/Vertical>} verticals
   */
  exports.prototype['verticals'] = undefined;
  /**
   * @member {String} cover_image_url
   */
  exports.prototype['cover_image_url'] = undefined;
  /**
   * @member {Number} events_count
   */
  exports.prototype['events_count'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {module:model/Country} country
   */
  exports.prototype['country'] = undefined;
  /**
   * @member {Boolean} show_calendar
   */
  exports.prototype['show_calendar'] = undefined;
  /**
   * @member {Boolean} show_flavours_filter
   */
  exports.prototype['show_flavours_filter'] = undefined;
  /**
   * @member {Number} show_filters_when_events_count
   */
  exports.prototype['show_filters_when_events_count'] = undefined;



  return exports;
}));


