/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Deeplink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Deeplink'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.DeeplinkApi = factory(root.MusementApi.ApiClient, root.MusementApi.Deeplink);
  }
}(this, function(ApiClient, Deeplink) {
  'use strict';

  /**
   * Deeplink service.
   * @module api/DeeplinkApi
   * @version 3.2.0
   */

  /**
   * Constructs a new DeeplinkApi. 
   * @alias module:api/DeeplinkApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the deeplinksGet operation.
     * @callback module:api/DeeplinkApi~deeplinksGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Deeplink} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get deeplink for a specific URL
     * @param {Number} url Relative URL base64 encoded
     * @param {module:api/DeeplinkApi~deeplinksGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Deeplink}
     */
    this.deeplinksGet = function(url, callback) {
      var postBody = null;

      // verify the required parameter 'url' is set
      if (url == undefined || url == null) {
        throw new Error("Missing the required parameter 'url' when calling deeplinksGet");
      }


      var pathParams = {
      };
      var queryParams = {
        'url': url
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/xml', 'application/json'];
      var accepts = ['application/xml', 'application/json'];
      var returnType = Deeplink;

      return this.apiClient.callApi(
        '/deeplinks', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
