/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Flavour'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Flavour'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.EditorialCategoriesApi = factory(root.MusementApi.ApiClient, root.MusementApi.Flavour);
  }
}(this, function(ApiClient, Flavour) {
  'use strict';

  /**
   * EditorialCategories service.
   * @module api/EditorialCategoriesApi
   * @version 3.2.0
   */

  /**
   * Constructs a new EditorialCategoriesApi. 
   * @alias module:api/EditorialCategoriesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the editorialCategoriesEditorialcategoryIdFlavoursGet operation.
     * @callback module:api/EditorialCategoriesApi~editorialCategoriesEditorialcategoryIdFlavoursGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Flavour} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all flavours connected to an editorial category
     * @param {Number} editorialcategoryId Editorial category identifier
     * @param {module:api/EditorialCategoriesApi~editorialCategoriesEditorialcategoryIdFlavoursGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Flavour}
     */
    this.editorialCategoriesEditorialcategoryIdFlavoursGet = function(editorialcategoryId, callback) {
      var postBody = null;

      // verify the required parameter 'editorialcategoryId' is set
      if (editorialcategoryId == undefined || editorialcategoryId == null) {
        throw new Error("Missing the required parameter 'editorialcategoryId' when calling editorialCategoriesEditorialcategoryIdFlavoursGet");
      }


      var pathParams = {
        'editorialcategoryId': editorialcategoryId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/xml', 'application/json'];
      var accepts = ['application/xml', 'application/json'];
      var returnType = Flavour;

      return this.apiClient.callApi(
        '/editorial-categories/{editorialcategoryId}/flavours', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
