/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GalleryMedia'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GalleryMedia'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.MediaApi = factory(root.MusementApi.ApiClient, root.MusementApi.GalleryMedia);
  }
}(this, function(ApiClient, GalleryMedia) {
  'use strict';

  /**
   * Media service.
   * @module api/MediaApi
   * @version 3.2.0
   */

  /**
   * Constructs a new MediaApi. 
   * @alias module:api/MediaApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the eventsEventIdMediaGet operation.
     * @callback module:api/MediaApi~eventsEventIdMediaGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/GalleryMedia>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all media for an event
     * @param {Number} eventId Event identifier
     * @param {module:api/MediaApi~eventsEventIdMediaGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/GalleryMedia>}
     */
    this.eventsEventIdMediaGet = function(eventId, callback) {
      var postBody = null;

      // verify the required parameter 'eventId' is set
      if (eventId == undefined || eventId == null) {
        throw new Error("Missing the required parameter 'eventId' when calling eventsEventIdMediaGet");
      }


      var pathParams = {
        'eventId': eventId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/xml', 'application/json'];
      var accepts = ['application/xml', 'application/json'];
      var returnType = [GalleryMedia];

      return this.apiClient.callApi(
        '/events/{eventId}/media', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
