/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PaypalPaymentRequest', 'model/SuccessfulPayment'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PaypalPaymentRequest'), require('../model/SuccessfulPayment'));
  } else {
    // Browser globals (root is window)
    if (!root.MusementApi) {
      root.MusementApi = {};
    }
    root.MusementApi.PaypalApi = factory(root.MusementApi.ApiClient, root.MusementApi.PaypalPaymentRequest, root.MusementApi.SuccessfulPayment);
  }
}(this, function(ApiClient, PaypalPaymentRequest, SuccessfulPayment) {
  'use strict';

  /**
   * Paypal service.
   * @module api/PaypalApi
   * @version 3.2.0
   */

  /**
   * Constructs a new PaypalApi. 
   * @alias module:api/PaypalApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the paymentsPaypalPaymentPost operation.
     * @callback module:api/PaypalApi~paymentsPaypalPaymentPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SuccessfulPayment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Pay an Order.
     * Pay an Order using Paypal.
     * @param {module:model/PaypalPaymentRequest} paypalPayment Paypal payment info request
     * @param {module:api/PaypalApi~paymentsPaypalPaymentPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SuccessfulPayment}
     */
    this.paymentsPaypalPaymentPost = function(paypalPayment, callback) {
      var postBody = paypalPayment;

      // verify the required parameter 'paypalPayment' is set
      if (paypalPayment == undefined || paypalPayment == null) {
        throw new Error("Missing the required parameter 'paypalPayment' when calling paymentsPaypalPaymentPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/xml', 'application/json'];
      var accepts = ['application/xml', 'application/json'];
      var returnType = SuccessfulPayment;

      return this.apiClient.callApi(
        '/payments/paypal/payment', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
