/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MusementApi);
  }
}(this, function(expect, MusementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MusementApi.Destination();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Destination', function() {
    it('should create an instance of Destination', function() {
      // uncomment below and update the code to test Destination
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be.a(MusementApi.Destination);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property verticals (base name: "verticals")', function() {
      // uncomment below and update the code to test the property verticals
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property saves (base name: "saves")', function() {
      // uncomment below and update the code to test the property saves
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property canonicalUrl (base name: "canonical_url")', function() {
      // uncomment below and update the code to test the property canonicalUrl
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property website (base name: "website")', function() {
      // uncomment below and update the code to test the property website
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property priceRange (base name: "price_range")', function() {
      // uncomment below and update the code to test the property priceRange
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property latitude (base name: "latitude")', function() {
      // uncomment below and update the code to test the property latitude
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property longitude (base name: "longitude")', function() {
      // uncomment below and update the code to test the property longitude
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property photos (base name: "photos")', function() {
      // uncomment below and update the code to test the property photos
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property comments (base name: "comments")', function() {
      // uncomment below and update the code to test the property comments
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property openingHours (base name: "opening_hours")', function() {
      // uncomment below and update the code to test the property openingHours
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property specialities (base name: "specialities")', function() {
      // uncomment below and update the code to test the property specialities
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

    it('should have the property rating (base name: "rating")', function() {
      // uncomment below and update the code to test the property rating
      //var instane = new MusementApi.Destination();
      //expect(instance).to.be();
    });

  });

}));
