/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MusementApi);
  }
}(this, function(expect, MusementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MusementApi.Event();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Event', function() {
    it('should create an instance of Event', function() {
      // uncomment below and update the code to test Event
      //var instane = new MusementApi.Event();
      //expect(instance).to.be.a(MusementApi.Event);
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property saves (base name: "saves")', function() {
      // uncomment below and update the code to test the property saves
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property relevance (base name: "relevance")', function() {
      // uncomment below and update the code to test the property relevance
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property relevanceVenue (base name: "relevanceVenue")', function() {
      // uncomment below and update the code to test the property relevanceVenue
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property maxConfirmationTime (base name: "maxConfirmationTime")', function() {
      // uncomment below and update the code to test the property maxConfirmationTime
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property mustSee (base name: "mustSee")', function() {
      // uncomment below and update the code to test the property mustSee
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property lastChance (base name: "lastChance")', function() {
      // uncomment below and update the code to test the property lastChance
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property topSeller (base name: "topSeller")', function() {
      // uncomment below and update the code to test the property topSeller
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property printVoucher (base name: "printVoucher")', function() {
      // uncomment below and update the code to test the property printVoucher
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property temporary (base name: "temporary")', function() {
      // uncomment below and update the code to test the property temporary
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property about (base name: "about")', function() {
      // uncomment below and update the code to test the property about
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property aboutMarkdown (base name: "aboutMarkdown")', function() {
      // uncomment below and update the code to test the property aboutMarkdown
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property aboutHtml (base name: "aboutHtml")', function() {
      // uncomment below and update the code to test the property aboutHtml
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property meetingPoint (base name: "meetingPoint")', function() {
      // uncomment below and update the code to test the property meetingPoint
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property openingHours (base name: "openingHours")', function() {
      // uncomment below and update the code to test the property openingHours
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property numberedSeats (base name: "numberedSeats")', function() {
      // uncomment below and update the code to test the property numberedSeats
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property hasPriceInfoOnDate (base name: "hasPriceInfoOnDate")', function() {
      // uncomment below and update the code to test the property hasPriceInfoOnDate
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property open (base name: "open")', function() {
      // uncomment below and update the code to test the property open
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property ticketNotIncluded (base name: "ticketNotIncluded")', function() {
      // uncomment below and update the code to test the property ticketNotIncluded
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property likelyToSellOut (base name: "likelyToSellOut")', function() {
      // uncomment below and update the code to test the property likelyToSellOut
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property specialOffer (base name: "specialOffer")', function() {
      // uncomment below and update the code to test the property specialOffer
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property exclusive (base name: "exclusive")', function() {
      // uncomment below and update the code to test the property exclusive
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property includedHotelNightNumber (base name: "includedHotelNightNumber")', function() {
      // uncomment below and update the code to test the property includedHotelNightNumber
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property greenFeeDays (base name: "greenFeeDays")', function() {
      // uncomment below and update the code to test the property greenFeeDays
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property daily (base name: "daily")', function() {
      // uncomment below and update the code to test the property daily
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property languages (base name: "languages")', function() {
      // uncomment below and update the code to test the property languages
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property groupSize (base name: "groupSize")', function() {
      // uncomment below and update the code to test the property groupSize
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property food (base name: "food")', function() {
      // uncomment below and update the code to test the property food
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property services (base name: "services")', function() {
      // uncomment below and update the code to test the property services
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property translated (base name: "translated")', function() {
      // uncomment below and update the code to test the property translated
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property features (base name: "features")', function() {
      // uncomment below and update the code to test the property features
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property highlights (base name: "highlights")', function() {
      // uncomment below and update the code to test the property highlights
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property included (base name: "included")', function() {
      // uncomment below and update the code to test the property included
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property notIncluded (base name: "notIncluded")', function() {
      // uncomment below and update the code to test the property notIncluded
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property isAvailableToday (base name: "isAvailableToday")', function() {
      // uncomment below and update the code to test the property isAvailableToday
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property isAvailableTomorrow (base name: "isAvailableTomorrow")', function() {
      // uncomment below and update the code to test the property isAvailableTomorrow
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property hasMultipleOptions (base name: "hasMultipleOptions")', function() {
      // uncomment below and update the code to test the property hasMultipleOptions
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property coverImageUrl (base name: "coverImageUrl")', function() {
      // uncomment below and update the code to test the property coverImageUrl
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property extraMediaUrl (base name: "extraMediaUrl")', function() {
      // uncomment below and update the code to test the property extraMediaUrl
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property retailPrice (base name: "retailPrice")', function() {
      // uncomment below and update the code to test the property retailPrice
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property netPrice (base name: "netPrice")', function() {
      // uncomment below and update the code to test the property netPrice
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property bundledPrice (base name: "bundledPrice")', function() {
      // uncomment below and update the code to test the property bundledPrice
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property discount (base name: "discount")', function() {
      // uncomment below and update the code to test the property discount
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property bucket (base name: "bucket")', function() {
      // uncomment below and update the code to test the property bucket
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property categories (base name: "categories")', function() {
      // uncomment below and update the code to test the property categories
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property reviewsNumber (base name: "reviewsNumber")', function() {
      // uncomment below and update the code to test the property reviewsNumber
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property reviewsAvg (base name: "reviewsAvg")', function() {
      // uncomment below and update the code to test the property reviewsAvg
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property reviewsAggregatedInfo (base name: "reviewsAggregatedInfo")', function() {
      // uncomment below and update the code to test the property reviewsAggregatedInfo
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property latitude (base name: "latitude")', function() {
      // uncomment below and update the code to test the property latitude
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property longitude (base name: "longitude")', function() {
      // uncomment below and update the code to test the property longitude
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property agencyUrls (base name: "agencyUrls")', function() {
      // uncomment below and update the code to test the property agencyUrls
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property agencyPrice (base name: "agencyPrice")', function() {
      // uncomment below and update the code to test the property agencyPrice
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property flavours (base name: "flavours")', function() {
      // uncomment below and update the code to test the property flavours
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property verticals (base name: "verticals")', function() {
      // uncomment below and update the code to test the property verticals
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property orderBoxElements (base name: "orderBoxElements")', function() {
      // uncomment below and update the code to test the property orderBoxElements
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property giftable (base name: "giftable")', function() {
      // uncomment below and update the code to test the property giftable
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property hasPassengerInfo (base name: "hasPassengerInfo")', function() {
      // uncomment below and update the code to test the property hasPassengerInfo
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property hasExtraCustomerData (base name: "hasExtraCustomerData")', function() {
      // uncomment below and update the code to test the property hasExtraCustomerData
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property realtimeCapable (base name: "realtimeCapable")', function() {
      // uncomment below and update the code to test the property realtimeCapable
      //var instane = new MusementApi.Event();
      //expect(instance).to.be();
    });

  });

}));
