/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MusementApi);
  }
}(this, function(expect, MusementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MusementApi.MusementList();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MusementList', function() {
    it('should create an instance of MusementList', function() {
      // uncomment below and update the code to test MusementList
      //var instane = new MusementApi.MusementList();
      //expect(instance).to.be.a(MusementApi.MusementList);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new MusementApi.MusementList();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new MusementApi.MusementList();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new MusementApi.MusementList();
      //expect(instance).to.be();
    });

    it('should have the property authors (base name: "authors")', function() {
      // uncomment below and update the code to test the property authors
      //var instane = new MusementApi.MusementList();
      //expect(instance).to.be();
    });

    it('should have the property views (base name: "views")', function() {
      // uncomment below and update the code to test the property views
      //var instane = new MusementApi.MusementList();
      //expect(instance).to.be();
    });

    it('should have the property scroll (base name: "scroll")', function() {
      // uncomment below and update the code to test the property scroll
      //var instane = new MusementApi.MusementList();
      //expect(instance).to.be();
    });

    it('should have the property saves (base name: "saves")', function() {
      // uncomment below and update the code to test the property saves
      //var instane = new MusementApi.MusementList();
      //expect(instance).to.be();
    });

    it('should have the property listType (base name: "list_type")', function() {
      // uncomment below and update the code to test the property listType
      //var instane = new MusementApi.MusementList();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new MusementApi.MusementList();
      //expect(instance).to.be();
    });

    it('should have the property coverImageUrl (base name: "cover_image_url")', function() {
      // uncomment below and update the code to test the property coverImageUrl
      //var instane = new MusementApi.MusementList();
      //expect(instance).to.be();
    });

    it('should have the property verticals (base name: "verticals")', function() {
      // uncomment below and update the code to test the property verticals
      //var instane = new MusementApi.MusementList();
      //expect(instance).to.be();
    });

  });

}));
