/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MusementApi);
  }
}(this, function(expect, MusementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MusementApi.PromoCode();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PromoCode', function() {
    it('should create an instance of PromoCode', function() {
      // uncomment below and update the code to test PromoCode
      //var instane = new MusementApi.PromoCode();
      //expect(instance).to.be.a(MusementApi.PromoCode);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instane = new MusementApi.PromoCode();
      //expect(instance).to.be();
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instane = new MusementApi.PromoCode();
      //expect(instance).to.be();
    });

    it('should have the property percentage (base name: "percentage")', function() {
      // uncomment below and update the code to test the property percentage
      //var instane = new MusementApi.PromoCode();
      //expect(instance).to.be();
    });

    it('should have the property discount (base name: "discount")', function() {
      // uncomment below and update the code to test the property discount
      //var instane = new MusementApi.PromoCode();
      //expect(instance).to.be();
    });

    it('should have the property maxUsage (base name: "maxUsage")', function() {
      // uncomment below and update the code to test the property maxUsage
      //var instane = new MusementApi.PromoCode();
      //expect(instance).to.be();
    });

    it('should have the property validFrom (base name: "validFrom")', function() {
      // uncomment below and update the code to test the property validFrom
      //var instane = new MusementApi.PromoCode();
      //expect(instance).to.be();
    });

    it('should have the property validUntil (base name: "validUntil")', function() {
      // uncomment below and update the code to test the property validUntil
      //var instane = new MusementApi.PromoCode();
      //expect(instance).to.be();
    });

    it('should have the property minimumAmount (base name: "minimumAmount")', function() {
      // uncomment below and update the code to test the property minimumAmount
      //var instane = new MusementApi.PromoCode();
      //expect(instance).to.be();
    });

  });

}));
