/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MusementApi);
  }
}(this, function(expect, MusementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MusementApi.ScheduleProduct();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScheduleProduct', function() {
    it('should create an instance of ScheduleProduct', function() {
      // uncomment below and update the code to test ScheduleProduct
      //var instane = new MusementApi.ScheduleProduct();
      //expect(instance).to.be.a(MusementApi.ScheduleProduct);
    });

    it('should have the property holderCode (base name: "holderCode")', function() {
      // uncomment below and update the code to test the property holderCode
      //var instane = new MusementApi.ScheduleProduct();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new MusementApi.ScheduleProduct();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new MusementApi.ScheduleProduct();
      //expect(instance).to.be();
    });

    it('should have the property productId (base name: "productId")', function() {
      // uncomment below and update the code to test the property productId
      //var instane = new MusementApi.ScheduleProduct();
      //expect(instance).to.be();
    });

    it('should have the property minBuy (base name: "minBuy")', function() {
      // uncomment below and update the code to test the property minBuy
      //var instane = new MusementApi.ScheduleProduct();
      //expect(instance).to.be();
    });

    it('should have the property maxBuy (base name: "maxBuy")', function() {
      // uncomment below and update the code to test the property maxBuy
      //var instane = new MusementApi.ScheduleProduct();
      //expect(instance).to.be();
    });

    it('should have the property availability (base name: "availability")', function() {
      // uncomment below and update the code to test the property availability
      //var instane = new MusementApi.ScheduleProduct();
      //expect(instance).to.be();
    });

    it('should have the property rawPrice (base name: "rawPrice")', function() {
      // uncomment below and update the code to test the property rawPrice
      //var instane = new MusementApi.ScheduleProduct();
      //expect(instance).to.be();
    });

    it('should have the property discountAmount (base name: "discountAmount")', function() {
      // uncomment below and update the code to test the property discountAmount
      //var instane = new MusementApi.ScheduleProduct();
      //expect(instance).to.be();
    });

    it('should have the property retailPrice (base name: "retailPrice")', function() {
      // uncomment below and update the code to test the property retailPrice
      //var instane = new MusementApi.ScheduleProduct();
      //expect(instance).to.be();
    });

    it('should have the property serviceFee (base name: "serviceFee")', function() {
      // uncomment below and update the code to test the property serviceFee
      //var instane = new MusementApi.ScheduleProduct();
      //expect(instance).to.be();
    });

  });

}));
