/**
 * Musement API
 * Musmement API
 *
 * OpenAPI spec version: 3.2.0
 * Contact: api-support@musement.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MusementApi);
  }
}(this, function(expect, MusementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MusementApi.BlogpostApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BlogpostApi', function() {
    describe('blogpostsCategoriesGet', function() {
      it('should call blogpostsCategoriesGet successfully', function(done) {
        //uncomment below and update the code to test blogpostsCategoriesGet
        //instance.blogpostsCategoriesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('blogpostsCategoriesIdGet', function() {
      it('should call blogpostsCategoriesIdGet successfully', function(done) {
        //uncomment below and update the code to test blogpostsCategoriesIdGet
        //instance.blogpostsCategoriesIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('blogpostsGet', function() {
      it('should call blogpostsGet successfully', function(done) {
        //uncomment below and update the code to test blogpostsGet
        //instance.blogpostsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('blogpostsIdGet', function() {
      it('should call blogpostsIdGet successfully', function(done) {
        //uncomment below and update the code to test blogpostsIdGet
        //instance.blogpostsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('blogpostsIdPositionGet', function() {
      it('should call blogpostsIdPositionGet successfully', function(done) {
        //uncomment below and update the code to test blogpostsIdPositionGet
        //instance.blogpostsIdPositionGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('citiesCityIdBlogpostsGet', function() {
      it('should call citiesCityIdBlogpostsGet successfully', function(done) {
        //uncomment below and update the code to test citiesCityIdBlogpostsGet
        //instance.citiesCityIdBlogpostsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
